import Head from 'next/head';
import { Roboto } from 'next/font/google';
import './globals.css';

const inter = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {inter}
      </Head>
      <body className={inter.fontFaces}>
        <main className='max-w-4xl mx-auto p-4'>
        {children}
        </main>
        </body>
    </html>
  );
}
